version: "3"

services:
    postgresdb:
        container_name: postgresdb
        image: "postgres"
        ports:
            - 5432:5432
        networks:
            - backend_network
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=userscrud
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=users
            - PGDATA=/usersdb
    users-app:
        container_name: users_app
        build:
            context: .
        volumes:
            - .:/app
        restart: always
        ports:
            - 8081:8081
        networks:
            - backend_network
        depends_on:
            - postgresdb

networks:
    backend_network:
      driver: "bridge"


